version: '2.3'
services:
  composer:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.composer
      target: composer
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="STRICT_TRANS_TABLES"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./config/docker/development-redis.conf:/usr/local/etc/redis/redis.conf
  web:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.web
      args:
        BUILDER_COMPOSER: my-docker_composer
    restart: always
    ports:
      - "9000:9000"
    environment:
      DB_NAME: wordpress
      DB_USER: mysql
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PREFIX: wp_
      WP_REDIS_FULL_PAGE_CACHE_TTL: 1
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_ENV: development
      WP_HOME: http://local.my-docker.se
      WP_SITEURL: http://local.my-docker.se/wp
      EP_HOST: http://elasticsearch:9200
    volumes:
      - .:/var/www
      - ./config/docker/development-php.ini:/usr/local/etc/php/php.ini
      - ./config/docker/development-phpfpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
  nginx:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.nginx
      args:
        BUILDER_COMPOSER: my-docker_composer
    restart: always
    depends_on:
      - redis
      - mysql
      - web
    ports:
      - "80:8080"
    volumes:
      - ./web:/var/www/web
      - ./config/docker/development-nginx.conf:/etc/nginx/nginx.conf
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
